#
# Makefile for num_value program
#

# the compiler
CC = gcc

# compiler flags
# -g 	adds debugging information
# -Wall turns on most compiler warnings
CFLAGS = -g -Wall

num_value: num_value.c num_value_func.c num_value.h
	$(CC) $(CFLAGS) -o num_value num_value.c num_value_func.c
